id: 3ff7ab34384e41e9abd240541fd97b36
initial_creation_type: ocr
source_metadata:
  volumes:
    c279fdb0eb2b4a7a8a283bf8e136fc43:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
